version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/api_service/static:/app/backend/api_service/staticfiles
      - ./backend/api_service/media:/app/backend/api_service/media

  frontend-organization-site:
    build:
      context: .
      dockerfile: ./docker/frontend/prod/organization-site/Dockerfile
    ports:
      - "3002:3000"
    env_file:
      - ./frontend/organization-site/.env.local
    volumes:
      - ./frontend/organization-site:/app/frontend/organization-site

  backend-api-service:
    build:
      context: .
      dockerfile: ./docker/backend/prod/api-service/Dockerfile
    ports:
      - "8002:8000"
    env_file:
      - ./backend/api_service/.env
    volumes:
      - ./backend/api_service:/app/backend/api_service

volumes:
  backups:
  static:
  media:
