version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ngtrydb
      POSTGRES_USER: ngtry
      POSTGRES_PASSWORD: ngtry
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ngtry -d ngtrydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/api_service/static:/app/backend/api_service/staticfiles
      - ./backend/api_service/media:/app/backend/api_service/media

  frontend-organization-site:
    build:
      context: .
      dockerfile: ./docker/frontend/prod/organization-site/Dockerfile
    ports:
      - "3002:3000"
    env_file:
      - ./frontend/organization-site/.env.local
    volumes:
      - ./frontend/organization-site:/app/frontend/organization-site

  backend-api-service:
    build:
      context: .
      dockerfile: ./docker/backend/prod/api-service/Dockerfile
    ports:
      - "8002:8000"
    env_file:
      - ./backend/api_service/.env
    volumes:
      - ./backend/api_service:/app/backend/api_service
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  backups:
  static:
  media:
